version: "3"

services:
  ifsolve:
    image: israelkleber/ifsolve_front-end
    ports:
      - "5173:5173"
    volumes:
      - .:/ifsolve
    environment:
      - VITE_API_URL=http://20.232.179.6:8000/
